PORTFOLIOS = {
    "genai": {
        "name": "GenAI Leaders",
        "description": "Top public companies in generative AI and enabling infrastructure.",
        "tickers": [
            "MSFT",
            "GOOGL",
            "AMZN",
            "META",
            "IBM",
            "ORCL",
            "CRM",
            "ADBE",
            "SNOW",
            "PLTR",
            "AI",
            "SOUN",
            "UPST",
            "TWLO",
            "OTEX",
            "SPLK",
            "ESTC",
            "AYX",
            "DDOG",
            "PATH",
            "NOW",
            "DOCU",
            "INTU",
            "SHOP",
            "ZM",
            "PINS",
            "SNAP",
            "LYFT",
            "UBER",
            "DASH",
            "CRWD",
            "FTNT",
            "PANW",
            "CHKP",
            "INTC",
            "NVDA",
            "AMD",
            "AVGO",
            "MU",
            "TSM",
            "QCOM",
            "MRVL",
            "ANET",
            "SMCI",
            "NTES",
            "BIDU",
            "0700.HK",
            "BABA",
        ],
        "diagnostic_assumptions": {
            "safe_zone_threshold": 2.99,
            "grey_zone_min": 1.81,
            "grey_zone_max": 2.99,
            "distress_zone_max": 1.80,
            "notes": "Altman Z-score thresholds are for public manufacturing companies. Interpret with caution for tech/software.",
        },
        "currency": "USD",
        "region": "US",
    }
}

DEFAULT_PORTFOLIO = "genai"
DEFAULT_START_DATE = "2025-01-02"
DEFAULT_END_DATE = "2025-05-20"
DEFAULT_DATE_RANGE = {"min": "2020-01-01", "max": "2025-05-21"}
