"""
File Manager - Handle output file organization and management

This module manages the organization, naming, and storage of all output files
generated by the Z-Score analysis pipeline.

Key Features:
- Automated file organization by ticker and date
- File naming conventions and versioning
- Output directory management
- File cleanup and archiving utilities
"""

import os
import shutil
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path

from ...common.logging_config import get_logger
from ...common.exceptions import OutputGenerationError

logger = get_logger(__name__)


class FileManager:
    """Manager for output file organization and storage."""
    
    def __init__(self, base_output_path: str = "output"):
        """
        Initialize file manager.
        
        Args:
            base_output_path: Base directory for all output files
        """
        self.base_path = Path(base_output_path)
        self.base_path.mkdir(exist_ok=True)
    
    def create_ticker_directory(self, ticker: str) -> Path:
        """
        Create and return ticker-specific directory.
        
        Args:
            ticker: Stock ticker symbol
            
        Returns:
            Path: Path to ticker directory
        """
        ticker_dir = self.base_path / ticker
        ticker_dir.mkdir(exist_ok=True)
        
        # Create subdirectories
        subdirs = ['reports', 'charts', 'data', 'llm_interactions']
        for subdir in subdirs:
            (ticker_dir / subdir).mkdir(exist_ok=True)
        
        logger.debug(f"Ticker directory structure created: {ticker_dir}")
        return ticker_dir
    
    def get_output_file_path(
        self, 
        ticker: str, 
        file_type: str, 
        extension: str,
        timestamp: Optional[datetime] = None
    ) -> Path:
        """
        Generate standardized output file path.
        
        Args:
            ticker: Stock ticker symbol
            file_type: Type of file (report, chart, data, etc.)
            extension: File extension
            timestamp: Optional timestamp for versioning
            
        Returns:
            Path: Standardized file path
        """
        ticker_dir = self.create_ticker_directory(ticker)
        
        if timestamp is None:
            timestamp = datetime.now()
        
        # Generate filename
        timestamp_str = timestamp.strftime("%Y%m%d_%H%M%S")
        filename = f"{ticker}_{file_type}_{timestamp_str}.{extension}"
        
        # Determine subdirectory
        subdir_map = {
            'report': 'reports',
            'chart': 'charts', 
            'data': 'data',
            'csv': 'data',
            'json': 'data',
            'summary': 'reports'
        }
        
        subdir = subdir_map.get(file_type, 'reports')
        file_path = ticker_dir / subdir / filename
        
        return file_path
    
    def list_ticker_files(self, ticker: str) -> Dict[str, List[Path]]:
        """
        List all files for a specific ticker.
        
        Args:
            ticker: Stock ticker symbol
            
        Returns:
            Dict[str, List[Path]]: Files organized by type
        """
        ticker_dir = self.base_path / ticker
        
        if not ticker_dir.exists():
            return {}
        
        files_by_type = {
            'reports': [],
            'charts': [],
            'data': [],
            'llm_interactions': []
        }
        
        for file_type in files_by_type.keys():
            type_dir = ticker_dir / file_type
            if type_dir.exists():
                files_by_type[file_type] = list(type_dir.glob('*'))
        
        return files_by_type
    
    def cleanup_old_files(self, ticker: str, days_to_keep: int = 30) -> int:
        """
        Clean up old files for a ticker.
        
        Args:
            ticker: Stock ticker symbol
            days_to_keep: Number of days of files to keep
            
        Returns:
            int: Number of files deleted
        """
        try:
            ticker_dir = self.base_path / ticker
            
            if not ticker_dir.exists():
                return 0
            
            cutoff_time = datetime.now().timestamp() - (days_to_keep * 24 * 3600)
            deleted_count = 0
            
            for file_path in ticker_dir.rglob('*'):
                if file_path.is_file() and file_path.stat().st_mtime < cutoff_time:
                    file_path.unlink()
                    deleted_count += 1
            
            logger.info(f"Cleaned up {deleted_count} old files for {ticker}")
            return deleted_count
            
        except Exception as e:
            error_msg = f"Failed to cleanup files for {ticker}: {str(e)}"
            logger.error(error_msg)
            raise OutputGenerationError(error_msg) from e
    
    def archive_ticker_data(self, ticker: str, archive_path: Optional[str] = None) -> str:
        """
        Archive all data for a ticker to a zip file.
        
        Args:
            ticker: Stock ticker symbol
            archive_path: Optional path for archive file
            
        Returns:
            str: Path to created archive
        """
        try:
            ticker_dir = self.base_path / ticker
            
            if not ticker_dir.exists():
                raise OutputGenerationError(f"No data found for ticker: {ticker}")
            
            if archive_path is None:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                archive_path = str(self.base_path / f"{ticker}_archive_{timestamp}.zip")
            
            # Create archive
            shutil.make_archive(
                archive_path.replace('.zip', ''),
                'zip',
                str(ticker_dir)
            )
            
            logger.info(f"Archive created: {archive_path}")
            return archive_path
            
        except Exception as e:
            error_msg = f"Failed to archive data for {ticker}: {str(e)}"
            logger.error(error_msg)
            raise OutputGenerationError(error_msg) from e
    
    def get_storage_summary(self) -> Dict[str, any]:
        """
        Get summary of storage usage.
        
        Returns:
            Dict: Storage summary information
        """
        try:
            total_size = 0
            ticker_count = 0
            file_count = 0
            
            for ticker_dir in self.base_path.iterdir():
                if ticker_dir.is_dir():
                    ticker_count += 1
                    for file_path in ticker_dir.rglob('*'):
                        if file_path.is_file():
                            total_size += file_path.stat().st_size
                            file_count += 1
            
            return {
                'total_size_mb': round(total_size / (1024 * 1024), 2),
                'ticker_count': ticker_count,
                'file_count': file_count,
                'base_path': str(self.base_path)
            }
            
        except Exception as e:
            logger.error(f"Failed to get storage summary: {str(e)}")
            return {}
